# Generated by Django 4.2.4 on 2023-09-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productversion',
            options={'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
    ]
